export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";

export const types = {
  ADD_FAVORITES : "ADD_FAVORITES",
  DELETE_FAVORITES : "DELETE_FAVORITES"
};
